Codesire-Deng/co_context

.gitignore, .vscode/launch.json, README.md, example/CMakeLists.txt, example/netcat.cpp, example/nop.cpp, example/nop_thread.cpp, example/rand4kr.cpp, example/rand4kr_blocking.cpp, example/rand4kr_callback.cpp, example/rand4kw_callback.cpp, include/co_context.hpp, include/co_context/config.hpp, include/co_context/lazy_io.hpp, include/co_context/log/log.hpp, include/co_context/main_task.hpp, include/co_context/task_info.hpp, include/uring.hpp, test/main.cpp
Add a thread-local buffer(std::queue) to handle the overflow task, including submission and completion.
Add a console logger to watch the internel state of co_context.
Known problem: For each thread, during a coro, the first time creating another coro would cost a lot of time, especially when cpu_affinity is enabled. It seems to be relative to operator new() and the OS scheduling.
现在，在提交/收割队列中溢出的任务将会被临时存储在线程独享的队列中（由 std::queue 实现）。
添加了新的分级 logger，类似 Android 的 log.d()，便于我们观察 co_context 内部每个线程的运行状态。
已知问题：每个线程第一次在协程内创建新的协程时，可能会有短暂暂停，在启用 cpu_affinity 时尤其明显，这可能与 operator new() 或者操作系统的调度有关。
=> Feat: tid-first sched

.vscode/settings.json, README.md, example/cv.cpp, example/cv_all.cpp, example/fingerprint.cpp, example/fingerprint_blocking.cpp, example/fingerprint_client.cpp, example/netcat.cpp, example/netcat_eager.cpp, example/netcat_eager_detach.cpp, example/netcat_timeout.cpp, example/sem.cpp, example/timeout.cpp, include/co_context/config.hpp, include/co_context/generator.hpp, test/ctx_swtch.cpp, test/generator_test.cpp, test/nop.cpp, test/rand4kr.cpp, test/rand4kr_blocking.cpp, test/rand4kr_callback.cpp, test/rand4kr_forloop.cpp, test/rand4kr_multithread_blocking.cpp, test/rand4kw_callback.cpp
feat: add generator.
fix(example): set all io_contexts' capacity to 32768.
---
`co_context::generator` is supposed to be equivalent to `std::generator` in the future C++23.
So you will simply replace `co_context` by `std` in the future.
=> feat: add generator.

CMakeLists.txt, lib/co_context/CMakeLists.txt, lib/co_context/io_context.cpp
/CMakeLists.txt now add an option for `mimalloc`. The default is `ON`, which means `mimalloc` version 2.0 or above is required.
=> build(cmake): make `mimalloc` an option

.vscode/settings.json, example/cv_notify_all.cpp, example/echo_server.cpp, example/netcat_eager_detach.cpp, example/sem.cpp, example/timer.cpp, include/co_context/io_context.hpp, lib/co_context/io_context.cpp
fix(example): replace `sleep_for` with `timeout`
feat(io_context): ctx will exit if tasks are over in 1-thread mode
=> Fix & Feat

example/netcat.cpp, include/co_context/detail/worker_meta.hpp, include/co_context/eager_io.hpp, include/co_context/generator.hpp, include/co_context/lazy_io.hpp, include/co_context/task.hpp, include/co_context/utility/timing.hpp, include/uring/sq_entry.hpp, include/uring/uring.hpp, include/uring/utility/io_helper.hpp, lib/co_context/net/socket.cpp, test/cat.cpp, test/coro_lifetime.cpp, test/ctx_swtch.cpp, test/generator_test.cpp, test/httpd.cpp, test/nc_uring.cpp, test/photon_streaming_client.cpp, test/swtch.cpp
- We introduce full supported SQE operations from [liburing](https://github.com/axboe/liburing), 74 syscalls in total. (`lazy_io` will support these 74 syscalls soon.)
- A hidden bug in co_spawned task is found and fixed. It once caused that the parameters of `task<void>` could not be deconstructed correctly
=> Full SQE Support in io_uring; Lifetime of task fixed

CMakeLists.txt
per
https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_C_KNOWN_FEATURES.html, c_std_17 was introduced in CMake 3.21, while the required CMake version is 3.20. which is packaged by RHEL/RockyLinux 9, so it would be nice if we could build with co_context on these distro releases using the shipped CMake.
so, in this change, CMAKE_C_STANDARD is changed from 17 to 11. this change should have minimum impact, as co_context is a C++20 project which does not contain C source code.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> build(cmake): lower CMAKE_C_STANDARD to 11

.clang-format, README.md, doc/README_en.md, include/co_context/co/condition_variable.hpp, include/co_context/detail/reap_info.hpp, include/co_context/io_context.hpp, include/uring/arch/syscall-defs.h, include/uring/detail/cq.hpp, include/uring/io_uring.h, include/uring/syscall.hpp, include/uring/uring.hpp
Update liburingcxx to catch up with liburing as of 2022/10/25.
- Catch up with fix of liburing from 2022/10/20 to 2022/10/25.
- Enhance performance for `_get_cq_entry()` with templated `has_ts` flag.
- Update clang-format to 15 and add some format styles.
- Add example for compilation.
=> Update liburingcxx to catch up with liburing.

include/co_context/task.hpp, test/coro_lifetime.cpp
- The move ctor of `task` had set a coroutine handle to another `task` by mistake. Now it is corrected.
- Drop an test case for coroutine lifetime. It had caused compilation failures.
=> fix a move constructor of `task`

CMakeLists.txt
- To speed up compilation for most of dev and usage of co_context, now ./test will not be built by default.
- You can turn on the `BUILD_TESTS` option in CMake to build tests.
=> build(cmake): do not build ./test by default

CMakeLists.txt, include/co_context/config.hpp, include/co_context/detail/lazy_io_awaiter.hpp, include/co_context/utility/time_cast.hpp, test/timer_accuracy.cpp
- Improve accuracy of timers using bias. (See config.hpp)
- Add test for the accuracy of timers.
- Do not use `CLOCK_BOOTTIME` time source for abs timers
=> Feat: More accurate timer

example/echo_server.cpp, example/echo_server_MT.cpp, example/netcat_timeout.cpp, example/redis_echo.cpp, example/redis_echo_MT.cpp, include/co_context/detail/lazy_io_awaiter.hpp, include/co_context/task.hpp, include/uring/sq_entry.hpp
- lazy_io can be `detach`ed now. That means you don't care the result of the IO AND you don't want to wait for it. It is useful when you have to close a fd.
=> Feat: add `detach` to lazy_io

CMakeLists.txt, cmake/CompileOption.cmake, cmake/Install.cmake, cmake/templates/Config.cmake.in, include/co_context/all.hpp
🎉🎉🎉 From now you can install co_context and then use `find_package(co_context)` in your own project:
1. Just run `cmake -B build && cmake --build build -j && sudo cmake --install build`.
2. Use `find_package(co_context)` in your CMakeLists.txt.
3. Write `target_link_libraries(${your_target} co_context::co_context)` for you target.
Another method is to `add_subdirectory(co_context)`:
1. Just copy this project to some subdirectory of your project.
2. Use `add_subdirectory(path/to/co_context)` in your CMakeLists.txt.
3. Write `target_link_libraries(${your_target} co_context::co_context)` for you target.
Please enjoy! 🥰
=> Provide `find_package` and `add_subdirectory`

.gitignore, CMakePresets.json
Add CMake preset for the convenience of debugging, benchmarking, and testing.
=> build(cmake): add CMake presets

example/when_any.cpp, example/when_some.cpp, include/co_context/co/when_any.hpp, include/co_context/utility/polymorphism.hpp
- Add `some(...)` to wait any number of tasks and get their results.
- Refactor `any(...)` for lower overhead.
=> feat(co): add `some(...)`

example/multi_fan_out.cpp, include/co_context/co/mutex.hpp, include/co_context/co/when_all.hpp, include/co_context/co/when_any.hpp, include/co_context/detail/lazy_io_awaiter.hpp, include/co_context/detail/type_traits.hpp, include/co_context/detail/worker_meta.hpp, include/co_context/io_context.hpp, include/co_context/shared_task.hpp, include/co_context/task.hpp, include/co_context/utility/mpl.hpp
- Introduce `shared_task` that can be co_awaited by multiple coroutines. This is similar with `std::shared_future`.
- Add `static_for` helpers in mpl.
- `all`, `some`, `any` now take the ownership of tasks.
=> feat(task): add `shared_task`

cmake/CompileOption.cmake, cmake/Platform.cmake, include/co_context/detail/lazy_io_awaiter.hpp, include/co_context/lazy_io.hpp, include/uring/compat.h, include/uring/compat.hpp, include/uring/sq_entry.hpp, include/uring/uring.hpp, include/uring/utility/kernel_version.hpp
- The missing linux header `<linux/openat2.h>` will not fail the compilation now. Instead, `openat2` will be removed from liburingcxx.
=> feat(uring): add openat2 compat

include/co_context/mpl/type_list.hpp, test/mpl_type_list.cpp
- Add last, drop_last, find_if, set and split to `type_list` with tests.
=> feat(mpl): more functors to type_list

include/co_context/co/when_any.hpp
编译时发现如下报错：
发现是因为没有include vector头文件
在when_any.hpp中include vector头文件
=> fix(co): include the <vector> header file

cmake/CompileOption.cmake, include/co_context/config.hpp, include/co_context/detail/compat.hpp, include/co_context/detail/spsc_cursor.hpp
Big thanks to @wangzhankun who helps to cross-compiling on RISC-V architecture:
1. No more `atomic<uint16_t>::is_always_lock_free` requirement on any architecture. (#88)
2. Fix [compat.hpp](https://github.com/Codesire-Deng/co_context/blob/main/include/co_context/detail/compat.hpp) for RISC-V. (#88)
3. Disable `-march=native` when cross-compiling. (#88)
4. No `is_loopback_only(INADDR_LOOPBACK)` by default. (#91)
=> Fix: compat for cross-compiling & RISC-V

include/co_context/config.hpp, include/co_context/utility/time_cast.hpp, include/uring/compat.hpp
feat(uring): compat kernel without `__kernel_timespec`. Thanks to @Lawliet828 . (#97)
=> feat(uring): compat kernel without `__kernel_timespec`. Thanks to Lawliet828
